spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:

  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  naver:
    accessKey: "KYLAUEXJ4BCUErigMPMS"
    secretKey: "rJATsm5fGM"

  admin:
    token: "AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC"

  jwt:
    secret:
      key: "7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA="