spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/post
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  config:
    import: jwt.yml

logging:
  level:
    org.hibernate.sql: debug