spring:
  batch:
    job:
      names: {job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    show-sql: true